sonar.projectKey=MatTrinkl_SE2Risiko
sonar.organization=mattrinkl

sonar.sources=shared/src/main,server/src/main,android-app/app/src/main
sonar.tests=shared/src/test,server/src/test,android-app/app/src/test

sonar.java.binaries=shared/build/classes,server/build/classes,android-app/app/build/intermediates/javac
sonar.kotlin.source.version=2.0

sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/**/*.xml,**/build/reports/coverage/**/*.xml
