sonar.projectKey=MatTrinkl_SE2Risiko
sonar.organization=mattrinkl
sonar.sources=shared/src/main,server/src/main,android-app/app/src/main
sonar.tests=shared/src/test,server/src/test,android-app/app/src/test
sonar.java.binaries=shared/build/classes/kotlin/main,server/build/classes/kotlin/main,android-app/app/build/tmp/kotlin-classes/debug,android-app/app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes
sonar.junit.reportPaths=shared/build/test-results/test,server/build/test-results/test,android-app/app/build/test-results/testDebugUnitTest
sonar.kotlin.source.version=2.0
sonar.coverage.jacoco.xmlReportPaths=shared/build/reports/jacoco/test/jacocoTestReport.xml,server/build/reports/jacoco/test/jacocoTestReport.xml,android-app/app/build/reports/jacoco/jacocoDebugUnitTestReport/jacocoDebugUnitTestReport.xml
